[package]
name = "commit_crafter"
version = "0.1.0"
edition = "2021"

description = "AI powered tool for Git commit message generator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
